gap_steering_node:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/drive"
    filtered_scan_topic: "/filtered_scan"
    limit_angle: 70.0
    kp: 1.1
    obstacle_distance_thresh: 1.0
    close_rays_thresh: 180
    far_rays_thresh: 40
    min_ray_distance: 3.0
    max_ray_distance: 9.0
    close_edges_thresh: 0.15
    right_left_distance_thresh: 0.4
    right_left_sides_angle: 90.0
    