gap_steering_node:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/drive"
    filtered_scan_topic: "/filtered_scan"
    limit_angle: 80.0
    kp: 1.1
    obstacle_distance_thresh: 1.2
    close_rays_thresh: 200
    far_rays_thresh: 40
    min_distance: 0.2
    max_distance: 12.0
    close_edges_thresh: 0.15
    right_left_distance_thresh: 0.4
    right_left_sides_angle: 90.0
    constant_speed: 1.0
