gap_steering_node:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/drive"
    filtered_scan_topic: "/filtered_scan"
    limit_angle: 70.0
    kp: 0.51
    kd: 1.1
    arc_length: 0.42
    number_of_critical_edges: 3
    obstacle_distance_thresh: 0.3
    min_distance: 0.8
    max_distance: 10.0
    min_vel: 0.3
    max_vel: 4.0

